### ISSUE TITLE
inkonsistente Kommentare

### ISSUE THREAD

**Issue by JesusJones92** [tpe-lecture/group-12#1]
Teilweise wurden Kommentare für JavaDoc mit Rückgabetyp (z.B. getX(), allerdings ohne Beschreibung) angegeben, teilweise wurden kein Rückgabetyp und keine Beschreibung kommentiert (z.B. getY()).
Parameter wurden meist auch nicht kommentiert.

**Comment by kshits** [comment]
Komplette java.util.* einzufügen ist nicht notwendig.

**Comment by thomsmits** [comment]
Alle Parameter und Rückgabetypen müssen kommentiert werden. Bei Parametern muss die Bedeutung des Parameters erläutert werden.
