### ISSUE TITLE
Division durch 0 in einheitsvektor

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group-12#11]
Eine mögliche Division durch 0 in der Methode `einheitsvektor()` wird nicht abgefangen.

**Comment by Axel94** [comment]
Wenn der Betrag 0 ist, wird in der Klasse public Vector einheitsvektor()  "null" zurückgeben. 

Ist dies so korrekt, oder gibt es eventuell bessere Lösungen ?

**Comment by thomsmits** [comment]
Da wir noch keine Exceptions haben, ist `null` wahrscheinlich eine brauchbare Lösung. Später würde man natürlich eine Ausnahme werfen.

**Comment by Nic48** [comment]
in meinem SourceTree werden rechts an der Seite "Hunks" angezeigt, wo aber die selbe Zeile 2 mal aufgezeigt wird (einmal rot hinterlegt, einmal grün). Kann man das einfach "discarden"? Ist ja keine wirkliche Änderung.
