### ISSUE TITLE
JavaDoc für die überschriebenen Methoden besser mit @see

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group-12#12]
Für die überschriebenen Methoden (`equals`, `hashCode` und `toString`) verwendet man normalerweise einen Querverweis auf die Original-Doku der Basisklasse.

z.B.

```java
/**
 * @see java.lang.Object#hashCode()
 */
````

**Comment by Noob48** [comment]
"@see java.lang.Object#hashCode()" wurde den 3 Methoden hinzugefügt.
