### ISSUE TITLE
toString() in Amount

### ISSUE THREAD

**Issue by Nic48** [tpe-lecture/group-12#13]
Amount f = new Amount(198000,Currencies.DOLLAR);
        Amount c = new Amount(-1000, Currencies.DOLLAR);

        System.out.println(c.subtract(f));
        --> gibt aus: --19 $

**Comment by Axel94** [comment]
Die Beträge von f und c werden als long eingelesen, da keine kein .00 hinter den Zahlen steht. 
D.h. die Beträge wurden nicht mehr mit 10000 multipliziert. 

Die Ausgabe in toString() in Amout hat zudem ein '-' zu viel an den String angehängt, da diese nur über getSign() geprüft wurde ob der Betrag + oder - ist. Wenn er negativ war,wurde ein '-' angehangen, jedoch hat eine negative Zahl eh schon ein '-', daher -- 19 $ anstatt  - 199000 $
