### ISSUE TITLE
TestAccounting

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-12#14]
Hi, hier ist euer Tutor:

Wie besprochen: Bitte ersetzt die Zeile 
"private static final int TEILER = tenTimes(Amount.getPrecision()  - 2);"
durch 
"private static final int TEILER = tenTimes(2);"
und korrigiert alles so, dass die Tests grün durchlaufen.

Je später ihr das macht, desto später kann ich bewerten. Am Besten wäre es, wenn ihr das bis 28.04. um 22:00 Uhr macht, dann kann ich am Mittwoch bewerten.

Vielen Dank und VG!

**Comment by Axel94** [comment]
Es wurden alle Fehler bis auf einen Rundungsfehler (Zeile 77) korrigiert. 
Das Problem hierbei ist, dass die Zahl 9516 erwartet wird, jedoch bei einer genauen Rechnung das Ergebnis 9515,632... beträgt. 
Wenn man das Ergebnis aufrundet, würde man jedoch Geld generieren. Auch wenn es nur sehr wenig wäre... Habe Herrn Smits diesbezüglich schon eine Email geschrieben. 

Ansonsten stimmt jetzt aber alles (Endlich auch die Signaturen von toDouble() und toLong() :+1: )
