### ISSUE TITLE
Quelltext enthält Tabs

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group-12#6]
Der Quelltext ist mit Tabs formatiert. Die Vorgabe ist eine Formatierung ohne Tabs und mit 4 Leerzeichen pro Ebene.

**Comment by Noob48** [comment]
Window-> Preferences -> Java -> Code Style -> Formatter -> Edit -> Indentation -> Tab policy -> Spaces only und Indentation size: 4. 
Würde dies die Formatierung dementsprechend anpassen? Ist "use spaces to indent wrapped lines" auch notwendig?

**Comment by thomsmits** [comment]
Zusätzlich sollte man in General -> Editors -> Text-Editors die Option "Insert spaces for tabs" setzen, damit der Text auch bei der Eingabe von Hand keine Tabs enthält.

**Comment by Noob48** [comment]
Einstellungen wurden angepasst
