### ISSUE TITLE
toString()-Methode ist falsch

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group-12#7]
Die `toString()`-Methode liefert falsche Ergebnisse. Das Anhängen einer 0 ist naiv und schlägt z.B. bei folgendem Vektor direkt fehl `Vector v = new Vector(2.55, 2.33, 2.22);`.

**Comment by Axel94** [comment]
Methode wurde überarbeitet. 
x,y,z werden nun als String gepeichert und es wird über deren Länge geprüft ob diese eine oder mehrere Nachkommastellen haben. Gegebenenfalls wird wieder eine "0" angehangen, was aber lediglich für die Ausgabe von Bedeutung ist.

**Comment by thomsmits** [comment]
Am einfachsten ist hier die Verwendung von String.format("%.2f", x) ...
