### ISSUE TITLE
Hash-Code streut nicht gut

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group-12#8]
Durch die Art, wie der Hash-Code berechnet wird, streuen die generierten Hash-Codes schlecht. Besser wäre folgende Implementierung:

```java
/**
  * @see java.lang.Object#hashCode()
  */
@Override
public int hashCode() {
    return Arrays.hashCode(new double[] { x, y, z } );
}
```

**Comment by Noob48** [comment]
Was bedeutet "streuen" im Zusammenhang mit der Hash-Code Methode? Inwiefern geschieht dies bei der von Ihnen gegebenen Implementierung nicht?
Die Implementierung wurde verbessert.

**Comment by thomsmits** [comment]
Die HashCodes müssen über den Wertebereich möglichst gleich verteilt sein. D.h. die 32 Bit voll ausnutzen. Einfaches Addieren und Casten bringt hier nichts. Die Implementierung von Arrays macht das deutlich besser.
